name: dlschool
channels:
  - pytorch
  - nvidia
dependencies:
  - python
  - scikit-learn
  - searborn
  - pandas
  - ipython
  - pytorch
  - jupyter
  - cudatoolkit=11.4
  - torchvision
  - numpy
  - matplotlib
  - scipy
  - h5py
